name: Flutter Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v3

      - name: Flutter Kur
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Paketleri Yükle
        run: flutter pub get

      - name: Web İçin Derle
        run: flutter build web --release --base-href "/"

      - name: GitHub Pages'e Yükle
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web